name: Deploy Staging
on:
  push:
    branches: ['release/v[0-9].[0-9]']
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/heads/release/}
      - name: Built, test, and deploy app
        uses: STEM-C/auto/build-test-deploy@v0.7.2
        with:
          image_tag: staging-${{ steps.get_version.outputs.VERSION }}
          app_name: casmm-staging
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
