name: Tag New Master Release
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag Master
        uses: STEM-C/auto/tag@v0.7.2
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
