name: Update Review App
on:
  pull_request:
    branches: [develop]
    types: [synchronize]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Get review app name
        id: get_name
        run: echo ::set-output name=NAME::review-pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
      - name: Built, test, and deploy app
        uses: STEM-C/auto/build-test-deploy@v0.7.2
        with:
          image_tag: ${{ steps.get_name.outputs.NAME }}
          app_name: ${{ steps.get_name.outputs.NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
